### ISSUE TITLE
Is it possible to create a new Merchant via this SDK?

### ISSUE THREAD

**Issue by nicodemuz** [paytrail/paytrail-php-sdk#10]
To create a payment for a Shop-in-Shop, one of the required data is a Merchant ID. Is it possible to create a new Merchant using this SDK in order to get a Merchant ID?

**Comment by loueranta-paytrail** [comment]
Paytrail's Merchant Creation API is separate from the Payment API, so there is no support for creating the sub merchants with this SDK.

**Comment by nicodemuz** [comment]
@loueranta-paytrail thanks! Can you provide a link to the API documentation or the SDK that supports this API call?

**Comment by loueranta-paytrail** [comment]
Unfortunately I'm not aware of any SDK that supports that functionality. 

However, the Merchant Creation API is quite simple compared to the Payment API, so implementation should be pretty straight forward even without SDK: https://services.paytrail.com/merchants/ext/docs/index.html
