### ISSUE TITLE
Support for Apple Pay?

### ISSUE THREAD

**Issue by nicodemuz** [paytrail/paytrail-php-sdk#11]
The docs mention about a `customProviders` response key. However, there does not seem to be any support for this? Does the SDK support Apple Pay payments?

**Comment by loueranta-paytrail** [comment]
Currently you can use Apple Pay on the Paytrail's hosted payment wall, where the user is redirected to make the payment method selection, but not with embedded payment method selection which is presented directly on the checkout page. 

However, we are planning on supporting the embedded option as well in the future.
