### ISSUE TITLE
Include signature validation in the response.php

### ISSUE THREAD

**Issue by Ciantic** [paytrail/paytrail-php-sdk#18]
Example's response.php is missing a signature check. This is very important:

```php
// Add this to response.php
$client = new Client(
    375917,
    'SAIPPUAKAUPPIAS',
    'php-sdk-test'
);

try {
    $client->validateHmac($_GET, '', $_GET["signature"]);
} catch (HmacException $e) {
    die("Signature validation failed");
}
```

I think I don't need to explain to developers here why it's important. 

However in my years I have used PayTrail, Checkout, Payment Highway, Luottokunta SDK's and I have noticed a pattern: When rookie developers use the SDKs they don't implement the signature verification on the callback url. 

Perhaps because they assume you can use some other parameter to check the validity, but that is not the case, signature must be checked to avoid spoofing.

It of course doesn't help if the example in the codebase omits the signature check completely. 

P.S. I made an example that uses purely the SDK (not extra classes), here: https://gist.github.com/Ciantic/f7e1087d3a8a742d7da66e92d9b7771c someone might be interested on it. It's not feature complete, but suffices for my purposes.

**Comment by loueranta-paytrail** [comment]
@Ciantic Thank you for bringing this up! We will add the signature validation to the code examples, as it is indeed an important feature to have.
