### ISSUE TITLE
Address $streetAddress exceeding 50 chars returns Request payload validation failed

### ISSUE THREAD

**Issue by tom890180** [paytrail/paytrail-php-sdk#19]
Hey,

If Paytrail\SDK\Model\Address $streetAddress is more than 50 chars, 400 Bad Request is returned with the message Request payload validation failed.

This isn't documented in https://docs.paytrail.com/#/?id=address nor on the Address class, it's also not validated on Address::validate().

Is this 50 max char unintentional, or accidentally not documented?

Thanks,
Tom

**Comment by loueranta-paytrail** [comment]
You are correct that there is a 50 character limit on the $streetAddress and the Paytrail API docs currently lack this information. 

We will update the docs and release an update on the PHP-SDK that reflects this (and other) field length limitations.

**Comment by loueranta-paytrail** [comment]
This was fixed in 2.1
