### ISSUE TITLE
Inconsistent types for MerchantId?

### ISSUE THREAD

**Issue by nicodemuz** [paytrail/paytrail-php-sdk#42]
When declaring commissions, the Merchant ID expects a string, whereas when initiating a client, the Merchant ID is expected to be an int.

https://github.com/paytrail/paytrail-php-sdk/blob/master/src/Client.php#L58
https://github.com/paytrail/paytrail-php-sdk/blob/master/src/Model/Commission.php#L59

**Comment by loueranta-paytrail** [comment]
This reflects the types defined in the [schema](https://docs.paytrail.com/#/) of the payment service.
