### ISSUE TITLE
requestSettlements() does not use search parameters

### ISSUE THREAD

**Issue by mpesari** [paytrail/paytrail-php-sdk#73]
**Describe the bug**

`Paytrail\SDK\Client->requestSettlements()` does not pass query parameters to `GET /settlements` endpoint.

**Steps to Reproduce**

```php
$response = $client->requestSettlements(
    (new SettlementRequest)
        ->setStartDate('2023-04-01')
        ->setEndDate('2023-04-17')
);
```

See list of *all* settlements instead of those in the given date range

**Expected behaviour**

Get settlements in the given date range, as returned by `Paytrail\SDK\Client->getSettlements()`.

**Comment by VuorelaJ-P** [comment]
Fixed in 2.5.1
